### ISSUE TITLE
[BUG] Rowaita dark action need fix

### ISSUE THREAD

**Issue by ZorinArch** [4e6anenk0/Rowaita-icon-theme#5]
Hi,

Action icons in Rowaita dark still in black and need to correct.

Thanks,

**Comment by 4e6anenk0** [comment]
I fixed the problem with black icons. I hope I didn't overlook some) The problem will be open for several days if a problem with color is suddenly found. Thanks.

**Comment by 4e6anenk0** [comment]
As I now understand, these are the icons that are in the `symbolic/actions` folder. Since everything is correct in Gnome, I did not immediately understand what the problem was. Yes, I see that Papyrus has white icons in this folder. Rowaita have differences in these icons, I will try to fix this bug soon

**Comment by 4e6anenk0** [comment]
Hi! Can you try the latest commit? I fixed `Rowaita-Dark`. The problem should be gone

**Comment by 4e6anenk0** [comment]
Please tell me in which graphical environment the problem occurs?  And can you attach screenshots?

**Comment by 4e6anenk0** [comment]
I found out what the problem was. But the strange thing is that Nautilus and Nemo didn't show this problem, unlike Dolphin. Different display and behavior with SVG files. Please tell me if everything is displayed well for you?
